name: 'PR Output'
description: 'Outputs markdown content to pull requests'
inputs:
  token:
    description: 'GitHub token'
    required: true
  sources:
    description: 'String with folders containing md files separated by commas (Supports glob pattern)'
    required: true
  name:
    description: 'Unique name for the specific output job'
    required: true
  top:
    required: false
    description: 'indicates if output should be on top of the description'
    default: 'false'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: edit-2
  color: green
